openapi: 3.0.1
info:
  title: BlogPostMCP
  version: 1.0.0
servers:
  - url: https://blogpostmcpapp-fhd2aeghdca3hdak.canadacentral-01.azurewebsites.net
paths:
  /generate-blogpost:
    post:
      summary: Generate a blog post from transcript
      description: Upload a transcript file to generate a blog post.
      operationId: generateBlogPost
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                transcript:
                  type: string
                  format: binary
                  description: Transcript file to upload
      responses:
        '200':
          description: Blog post generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: How to use MCP with Power Apps
                  url:
                    type: string
                    example: https://blobstorageurl/path/to/generated.docx
