swagger: '2.0'
info:
  title: BlogPostMCP
  description: MCP Server for generating blog posts from transcript files via Copilot Studio
  version: 1.0.0
host: blogpostmcpapp-fhd2aeghdca3hdak.canadacentral-01.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /generate-blog:
    post:
      summary: Generate blog post from transcript
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: transcript
          in: formData
          description: Transcript file (text format)
          required: true
          type: file
      responses:
        '200':
          description: Successful generation
          schema:
            type: object
            properties:
              url:
                type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
